In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [55]:
df = pd.read_csv("churn.csv")

In [56]:
df.head()

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,,43,2,125510.82,1,1,1,79084.10,0

In [57]:
df.shape

(10000, 12)

In [58]:
df.columns

Index(['customer_id', 'credit_score', 'country', 'gender', 'age', 'tenure',
       'balance', 'products_number', 'credit_card', 'active_member',
       'estimated_salary', 'churn'],
      dtype='object')

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       10000 non-null  int64
 1   credit_score      9991 non-null   object
 2   country           9998 non-null   object
 3   gender            9999 non-null   object
 4   age               9999 non-null   object
 5   tenure            9999 non-null   object
 6   balance           9991 non-null   float64
 7   products_number   10000 non-null  object
 8   credit_card       10000 non-null  int64
 9   active_member     10000 non-null  int64
 10  estimated_salary  10000 non-null  float64
 11  churn             10000 non-null  int64
dtypes: float64(2), int64(4), object(6)
memory usage: 937.6+ KB

In [60]:
df.drop('customer_id',axis=1,inplace=True)

In [61]:
df.columns

Index(['credit_score', 'country', 'gender', 'age', 'tenure', 'balance',
       'products_number', 'credit_card', 'active_member', 'estimated_salary',
       'churn'],
      dtype='object')

In [62]:
df.isnull().sum()

credit_score        9
country             2
gender              1
age                 1
tenure              1
balance             9
products_number     0
credit_card         0
active_member       0
estimated_salary    0
churn               0
dtype: int64

In [63]:
df['credit_score'] = pd.to_numeric(df['credit_score'], errors='coerce')
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['tenure'] = pd.to_numeric(df['tenure'], errors='coerce')
df['balance'] = pd.to_numeric(df['balance'], errors='coerce')
df['products_number'] = pd.to_numeric(df['products_number'], errors='coerce')

In [64]:
df['credit_score'].fillna(df['credit_score'].mean(), inplace=True)
df['age'].fillna(df['age'].mean(), inplace=True)
df['tenure'].fillna(df['tenure'].mean(), inplace=True)
df['balance'].fillna(df['balance'].mean(), inplace=True)
df['products_number'].fillna(df['products_number'].mode()[0], inplace=True)

/tmp/ipykernel_7174/3968884133.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['credit_score'].fillna(df['credit_score'].mean(), inplace=True)
/tmp/ipykernel_7174/3968884133.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(), inplace=True)
/tmp/ipykernel_7174/3968884133.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['tenure'].fillna(df['tenure'].mean(), inplace=True)
/tmp/ipykernel_7174/3968884133.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['balance'].fillna(df['balance'].mean(), inplace=True)
/tmp/ipykernel_7174/3968884133.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['products_number'].fillna(df['products_number'].mode()[0], inplace=True)

In [65]:
df['credit_score'] = df['credit_score'].round().astype(int)

In [66]:
df['country'].fillna(df['country'].mode()[0], inplace=True)
df['gender'].fillna(df['gender'].mode()[0], inplace=True)

/tmp/ipykernel_7174/921262624.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['country'].fillna(df['country'].mode()[0], inplace=True)
/tmp/ipykernel_7174/921262624.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna(df['gender'].mode()[0], inplace=True)

In [67]:
df['gender'] = df['gender'].astype('category')
df['country'] = df['country'].astype('category')

In [68]:
df['gender'].unique()

['Female', '       ', 'Male']
Categories (3, object): ['       ', 'Female', 'Male']

In [69]:
df['gender'] = df['gender'].astype(str)

In [70]:
df['gender'] = df['gender'].replace(r'^\s*$', np.nan, regex=True)

In [71]:
df['gender'] = df['gender'].str.strip().str.capitalize()

In [72]:
df['gender'] = df['gender'].astype('category')

In [73]:
df['gender'].unique()

['Female', NaN, 'Male']
Categories (2, object): ['Female', 'Male']

In [74]:
df['gender'].fillna(df['gender'].mode()[0], inplace=True)

/tmp/ipykernel_7174/3191725845.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna(df['gender'].mode()[0], inplace=True)

In [75]:
df['gender'].unique()

['Female', 'Male']
Categories (2, object): ['Female', 'Male']

In [76]:
df = df[(df['age'] >= 18) & (df['age'] <= 75)]

In [77]:
df.duplicated().sum()

np.int64(0)

In [78]:
df.duplicated().sum()

np.int64(0)

In [79]:
df

,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,619,France,Female,42.0,2.0,0.00,1.0,1,1,101348.88,1
1,608,Spain,Female,41.0,1.0,83807.86,1.0,0,1,112542.58,0
2,502,France,Female,42.0,8.0,159660.80,3.0,1,0,113931.57,1
3,651,France,Female,39.0,1.0,0.00,2.0,0,0,93826.63,0
4,850,Spain,Male,43.0,2.0,125510.82,1.0,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39.0,5.0,0.00,2.0,1,0,96270.64,0
9996,516,France,Male,35.0,10.0,57369.61,1.0,1,1,101699.77,0
9997,709,France,Female,36.0,7.0,0.00,1.0,0,1,42085.58,1
9998,772,Germany,Male,42.0,3.0,75075.31,2.0,1,0,92888.52,1
9999,792,France,Female,28.0,4.0,130142.79,1.0,1,0,38190.78,0

In [82]:
df.dtypes

credit_score           int64
country             category
gender              category
age                  float64
tenure               float64
balance              float64
products_number      float64
credit_card            int64
active_member          int64
estimated_salary     float64
churn                  int64
dtype: object

In [80]:
df.isnull().sum()

credit_score        0
country             0
gender              0
age                 0
tenure              0
balance             0
products_number     0
credit_card         0
active_member       0
estimated_salary    0
churn               0
dtype: int64

In [81]:
df.to_csv("churn_cleaned.csv", index=False)